import tkinter
import tkinter.messagebox
import random
import pyperclip #this library is used to directly past or copy any text to clipboard
# ---------------------------- PASSWORD GENERATOR ------------------------------- #
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols = ['!', '#', '$', '%', '&', '(', ')', '*', '+']
def password_generator():
    nr_letters = random.randint(8, 10)
    nr_symbols = random.randint(2, 4)
    nr_numbers = random.randint(2, 4)

    password_list = []  #password size is from min 12 char to max 18 char
    password_letters = [random.choice(letters) for char in range(nr_letters) ] #list comprehension
    password_numbers = [random.choice(numbers) for char in range(nr_numbers) ] 
    password_symbols = [random.choice(symbols) for char in range(nr_symbols) ]
    password_list = password_letters + password_numbers + password_symbols

    random.shuffle(password_list)
    password = "".join(password_list) #this a shortcut to joins string will either list elements or tuple or even dict elements
    # if mylist = ["1","2","3"] then pass = "#".join(mylist) ---->>>gives>>> pass-->>>"1#2#3"

    password_input.insert(0,password) #change entry values when btn password generator is clicked
    pyperclip.copy(password) #this copies password directly to clipboard and we can paste it using ctrl+v

# ---------------------------- SAVE PASSWORD ------------------------------- #
def add_data_to_file():
    if len(website_input.get()) == 0 or len(user_detail_input.get()) == 0 or len(password_input.get()) == 0:
        warning = tkinter.messagebox.showinfo(title = "Warning", message = "Enter your details, Don't leave fields empty")
        print("Enter Details Please")
    else:
        #these popups generated by tkinter are called standard dialogs
        confirmation_of_details = tkinter.messagebox.askokcancel(title= "Confirmation", message = f"These are the details:"+
        f"\nWebsite:    {website_input.get()}\nUser:\t   {user_detail_input.get()}\nPassword:  {password_input.get()}\nAre you Sure?")
        # print(type(confirmation_of_details))
        if confirmation_of_details:
            #save info in a txt file
            with open(file="./Day29/file_for_passwords.txt",mode="a") as file:
                file.write(f"{website_input.get()}\t|\t{user_detail_input.get()}\t|\t{password_input.get()}\n")
                website_input.delete(0,50) #this will delete the up to 50 characters in this Entry section after add btn has been clicked
                password_input.delete(0,50)
                print("Password Added to File")
        pass
        

# ---------------------------- UI SETUP ------------------------------- #
window = tkinter.Tk()
window.title("Password Manager")
# window.minsize(width=550,height=400)
window.config(padx= 50, pady= 50)

# image on canvas
my_canvas = tkinter.Canvas(height=200 , width=200)  
my_image = tkinter.PhotoImage(file="./Day29/logo.png")
my_canvas.create_image(100,100,image=my_image)
my_canvas.grid(column=1,row=0)
#text on window
website_txt = tkinter.Label(text="Website: ")
website_txt.grid(column=0,row=1)

user_detail_txt = tkinter.Label(text="Username/Email: ")
user_detail_txt.grid(column=0,row=2)

password_txt = tkinter.Label(text="Password: ")
password_txt.grid(column=0,row=3)

#website name input
website_input = tkinter.Entry(width=54)
website_input.grid(column=1,row=1,columnspan=2)
website_input.focus()#using this when gui has started, one can directly start typing in this Entry
#user detail input
user_detail_input = tkinter.Entry(width=54)
user_detail_input.grid(column=1,row=2,columnspan=2)
user_detail_input.insert(0,"yashkun@gmail.com")#this shows up in this entry from the start of GUI

#password input
password_input = tkinter.Entry(width=34)
password_input.grid(column= 1,row=3 )

#Buttons on window

#password generation button
generate_password_btn = tkinter.Button(text="Password Generator",command=password_generator)
generate_password_btn.grid(column=2,row=3)

#add password to text.file button
add_btn = tkinter.Button(text="Add",width=46,command=add_data_to_file)
add_btn.grid(column=1,row=5,columnspan=2) 


window.mainloop()